### ISSUE TITLE
Backwards incompatible relation name change

### ISSUE THREAD

**Issue by claudiubelu** [canonical/landscape-client-charm#9]
Previous revisions of the ``landscape-client-charm`` had the ``container`` relation name [1], while the recent revisions changed it to ``mycontainer`` [2]. This breaks previous deployments:

```
cannot add relation between "landscape-client:container" and "landscape-postgresql:juju-info": application "landscape-client" has no "container" relation
```

[1] https://bazaar.launchpad.net/~landscape/landscape-client-charm/trunk/view/head:/metadata.yaml#L18
[2] https://github.com/canonical/landscape-client-charm/blob/ac6dada540362b02be552eb0f136acf7895939b0/metadata.yaml#L24

**Comment by silverdrake11** [comment]
Pull request is here https://github.com/canonical/landscape-client-charm/pull/11

**Comment by claudiubelu** [comment]
Issue has been resolved.
